services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d my_db"]
      interval: 15s
      timeout: 10s
      retries: 5


  django_api:
    build: .
    restart: always
    environment:
      DB_NAME: my_db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_PORT: 5432
      DB_HOST: db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
