# Generated by Django 5.0.1 on 2024-02-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de Crédito', 'Cartão de Crédito'), ('PIX', 'PIX'), ('Boleto', 'Boleto')], default='PIX', max_length=30),
        ),
    ]
