# Generated by Django 5.0.1 on 2024-02-02 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_paymentmethods_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_method_order', to='orders.paymentmethod'),
        ),
    ]
