# Generated by Django 5.0.1 on 2024-02-02 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_delete_paymentmethod'),
        ('payment_methods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_methods.paymentmethod'),
        ),
    ]
