# Generated by Django 5.0.1 on 2024-02-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_each_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='each_product_quantity',
            field=models.JSONField(),
        ),
    ]
