# Generated by Django 5.0.1 on 2024-01-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('warrant_period', models.CharField(max_length=100)),
            ],
        ),
    ]
